// File generated from our OpenAPI spec by Stainless.

package com.post_for_me.api.models.socialaccountfeeds

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.post_for_me.api.core.JsonValue
import com.post_for_me.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PlatformPostTest {

    @Test
    fun create() {
        val platformPost =
            PlatformPost.builder()
                .caption("caption")
                .addMedia(listOf(JsonValue.from(mapOf<String, Any>())))
                .platform("platform")
                .platformAccountId("platform_account_id")
                .platformPostId("platform_post_id")
                .platformUrl("platform_url")
                .socialAccountId("social_account_id")
                .externalAccountId("external_account_id")
                .externalPostId("external_post_id")
                .metrics(
                    PlatformPost.Metrics.TikTokBusinessMetricsDto.builder()
                        .addressClicks(0.0)
                        .appDownloadClicks(0.0)
                        .addAudienceCity(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceCity.builder()
                                .cityName("city_name")
                                .percentage(0.0)
                                .build()
                        )
                        .addAudienceCountry(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceCountry.builder()
                                .country("country")
                                .percentage(0.0)
                                .build()
                        )
                        .addAudienceGender(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceGender.builder()
                                .gender("gender")
                                .percentage(0.0)
                                .build()
                        )
                        .addAudienceType(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceType.builder()
                                .percentage(0.0)
                                .type("type")
                                .build()
                        )
                        .averageTimeWatched(0.0)
                        .comments(0.0)
                        .emailClicks(0.0)
                        .addEngagementLike(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.EngagementLike.builder()
                                .percentage(0.0)
                                .second("second")
                                .build()
                        )
                        .favorites(0.0)
                        .fullVideoWatchedRate(0.0)
                        .addImpressionSource(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.ImpressionSource.builder()
                                .impressionSource("impression_source")
                                .percentage(0.0)
                                .build()
                        )
                        .leadSubmissions(0.0)
                        .likes(0.0)
                        .newFollowers(0.0)
                        .phoneNumberClicks(0.0)
                        .profileViews(0.0)
                        .reach(0.0)
                        .shares(0.0)
                        .totalTimeWatched(0.0)
                        .addVideoViewRetention(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.VideoViewRetention
                                .builder()
                                .percentage(0.0)
                                .second("second")
                                .build()
                        )
                        .videoViews(0.0)
                        .websiteClicks(0.0)
                        .build()
                )
                .platformData(PlatformPost.PlatformData.builder().title("title").build())
                .postedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .socialPostId("social_post_id")
                .socialPostResultId("social_post_result_id")
                .build()

        assertThat(platformPost.caption()).isEqualTo("caption")
        assertThat(platformPost.media())
            .containsExactly(listOf(JsonValue.from(mapOf<String, Any>())))
        assertThat(platformPost.platform()).isEqualTo("platform")
        assertThat(platformPost.platformAccountId()).isEqualTo("platform_account_id")
        assertThat(platformPost.platformPostId()).isEqualTo("platform_post_id")
        assertThat(platformPost.platformUrl()).isEqualTo("platform_url")
        assertThat(platformPost.socialAccountId()).isEqualTo("social_account_id")
        assertThat(platformPost.externalAccountId()).isEqualTo("external_account_id")
        assertThat(platformPost.externalPostId()).isEqualTo("external_post_id")
        assertThat(platformPost.metrics())
            .isEqualTo(
                PlatformPost.Metrics.ofTikTokBusinessMetricsDto(
                    PlatformPost.Metrics.TikTokBusinessMetricsDto.builder()
                        .addressClicks(0.0)
                        .appDownloadClicks(0.0)
                        .addAudienceCity(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceCity.builder()
                                .cityName("city_name")
                                .percentage(0.0)
                                .build()
                        )
                        .addAudienceCountry(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceCountry.builder()
                                .country("country")
                                .percentage(0.0)
                                .build()
                        )
                        .addAudienceGender(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceGender.builder()
                                .gender("gender")
                                .percentage(0.0)
                                .build()
                        )
                        .addAudienceType(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceType.builder()
                                .percentage(0.0)
                                .type("type")
                                .build()
                        )
                        .averageTimeWatched(0.0)
                        .comments(0.0)
                        .emailClicks(0.0)
                        .addEngagementLike(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.EngagementLike.builder()
                                .percentage(0.0)
                                .second("second")
                                .build()
                        )
                        .favorites(0.0)
                        .fullVideoWatchedRate(0.0)
                        .addImpressionSource(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.ImpressionSource.builder()
                                .impressionSource("impression_source")
                                .percentage(0.0)
                                .build()
                        )
                        .leadSubmissions(0.0)
                        .likes(0.0)
                        .newFollowers(0.0)
                        .phoneNumberClicks(0.0)
                        .profileViews(0.0)
                        .reach(0.0)
                        .shares(0.0)
                        .totalTimeWatched(0.0)
                        .addVideoViewRetention(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.VideoViewRetention
                                .builder()
                                .percentage(0.0)
                                .second("second")
                                .build()
                        )
                        .videoViews(0.0)
                        .websiteClicks(0.0)
                        .build()
                )
            )
        assertThat(platformPost.platformData())
            .isEqualTo(PlatformPost.PlatformData.builder().title("title").build())
        assertThat(platformPost.postedAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(platformPost.socialPostId()).isEqualTo("social_post_id")
        assertThat(platformPost.socialPostResultId()).isEqualTo("social_post_result_id")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val platformPost =
            PlatformPost.builder()
                .caption("caption")
                .addMedia(listOf(JsonValue.from(mapOf<String, Any>())))
                .platform("platform")
                .platformAccountId("platform_account_id")
                .platformPostId("platform_post_id")
                .platformUrl("platform_url")
                .socialAccountId("social_account_id")
                .externalAccountId("external_account_id")
                .externalPostId("external_post_id")
                .metrics(
                    PlatformPost.Metrics.TikTokBusinessMetricsDto.builder()
                        .addressClicks(0.0)
                        .appDownloadClicks(0.0)
                        .addAudienceCity(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceCity.builder()
                                .cityName("city_name")
                                .percentage(0.0)
                                .build()
                        )
                        .addAudienceCountry(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceCountry.builder()
                                .country("country")
                                .percentage(0.0)
                                .build()
                        )
                        .addAudienceGender(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceGender.builder()
                                .gender("gender")
                                .percentage(0.0)
                                .build()
                        )
                        .addAudienceType(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceType.builder()
                                .percentage(0.0)
                                .type("type")
                                .build()
                        )
                        .averageTimeWatched(0.0)
                        .comments(0.0)
                        .emailClicks(0.0)
                        .addEngagementLike(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.EngagementLike.builder()
                                .percentage(0.0)
                                .second("second")
                                .build()
                        )
                        .favorites(0.0)
                        .fullVideoWatchedRate(0.0)
                        .addImpressionSource(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.ImpressionSource.builder()
                                .impressionSource("impression_source")
                                .percentage(0.0)
                                .build()
                        )
                        .leadSubmissions(0.0)
                        .likes(0.0)
                        .newFollowers(0.0)
                        .phoneNumberClicks(0.0)
                        .profileViews(0.0)
                        .reach(0.0)
                        .shares(0.0)
                        .totalTimeWatched(0.0)
                        .addVideoViewRetention(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.VideoViewRetention
                                .builder()
                                .percentage(0.0)
                                .second("second")
                                .build()
                        )
                        .videoViews(0.0)
                        .websiteClicks(0.0)
                        .build()
                )
                .platformData(PlatformPost.PlatformData.builder().title("title").build())
                .postedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .socialPostId("social_post_id")
                .socialPostResultId("social_post_result_id")
                .build()

        val roundtrippedPlatformPost =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(platformPost),
                jacksonTypeRef<PlatformPost>(),
            )

        assertThat(roundtrippedPlatformPost).isEqualTo(platformPost)
    }
}
