// File generated from our OpenAPI spec by Stainless.

package com.post_for_me.api.models.socialaccountfeeds

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.post_for_me.api.core.JsonValue
import com.post_for_me.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SocialAccountFeedListResponseTest {

    @Test
    fun create() {
        val socialAccountFeedListResponse =
            SocialAccountFeedListResponse.builder()
                .addData(
                    PlatformPost.builder()
                        .caption("caption")
                        .addMedia(listOf(JsonValue.from(mapOf<String, Any>())))
                        .platform("platform")
                        .platformAccountId("platform_account_id")
                        .platformPostId("platform_post_id")
                        .platformUrl("platform_url")
                        .socialAccountId("social_account_id")
                        .externalAccountId("external_account_id")
                        .externalPostId("external_post_id")
                        .metrics(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.builder()
                                .addressClicks(0.0)
                                .appDownloadClicks(0.0)
                                .addAudienceCity(
                                    PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceCity
                                        .builder()
                                        .cityName("city_name")
                                        .percentage(0.0)
                                        .build()
                                )
                                .addAudienceCountry(
                                    PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceCountry
                                        .builder()
                                        .country("country")
                                        .percentage(0.0)
                                        .build()
                                )
                                .addAudienceGender(
                                    PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceGender
                                        .builder()
                                        .gender("gender")
                                        .percentage(0.0)
                                        .build()
                                )
                                .addAudienceType(
                                    PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceType
                                        .builder()
                                        .percentage(0.0)
                                        .type("type")
                                        .build()
                                )
                                .averageTimeWatched(0.0)
                                .comments(0.0)
                                .emailClicks(0.0)
                                .addEngagementLike(
                                    PlatformPost.Metrics.TikTokBusinessMetricsDto.EngagementLike
                                        .builder()
                                        .percentage(0.0)
                                        .second("second")
                                        .build()
                                )
                                .favorites(0.0)
                                .fullVideoWatchedRate(0.0)
                                .addImpressionSource(
                                    PlatformPost.Metrics.TikTokBusinessMetricsDto.ImpressionSource
                                        .builder()
                                        .impressionSource("impression_source")
                                        .percentage(0.0)
                                        .build()
                                )
                                .leadSubmissions(0.0)
                                .likes(0.0)
                                .newFollowers(0.0)
                                .phoneNumberClicks(0.0)
                                .profileViews(0.0)
                                .reach(0.0)
                                .shares(0.0)
                                .totalTimeWatched(0.0)
                                .addVideoViewRetention(
                                    PlatformPost.Metrics.TikTokBusinessMetricsDto.VideoViewRetention
                                        .builder()
                                        .percentage(0.0)
                                        .second("second")
                                        .build()
                                )
                                .videoViews(0.0)
                                .websiteClicks(0.0)
                                .build()
                        )
                        .postedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .socialPostId("social_post_id")
                        .socialPostResultId("social_post_result_id")
                        .build()
                )
                .meta(
                    SocialAccountFeedListResponse.Meta.builder()
                        .cursor("cursor")
                        .limit(0.0)
                        .next("https://api.postforme.dev/v1/items?cursor=pgn_xxxxx&limit=10")
                        .hasMore(true)
                        .build()
                )
                .build()

        assertThat(socialAccountFeedListResponse.data())
            .containsExactly(
                PlatformPost.builder()
                    .caption("caption")
                    .addMedia(listOf(JsonValue.from(mapOf<String, Any>())))
                    .platform("platform")
                    .platformAccountId("platform_account_id")
                    .platformPostId("platform_post_id")
                    .platformUrl("platform_url")
                    .socialAccountId("social_account_id")
                    .externalAccountId("external_account_id")
                    .externalPostId("external_post_id")
                    .metrics(
                        PlatformPost.Metrics.TikTokBusinessMetricsDto.builder()
                            .addressClicks(0.0)
                            .appDownloadClicks(0.0)
                            .addAudienceCity(
                                PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceCity.builder()
                                    .cityName("city_name")
                                    .percentage(0.0)
                                    .build()
                            )
                            .addAudienceCountry(
                                PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceCountry
                                    .builder()
                                    .country("country")
                                    .percentage(0.0)
                                    .build()
                            )
                            .addAudienceGender(
                                PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceGender
                                    .builder()
                                    .gender("gender")
                                    .percentage(0.0)
                                    .build()
                            )
                            .addAudienceType(
                                PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceType.builder()
                                    .percentage(0.0)
                                    .type("type")
                                    .build()
                            )
                            .averageTimeWatched(0.0)
                            .comments(0.0)
                            .emailClicks(0.0)
                            .addEngagementLike(
                                PlatformPost.Metrics.TikTokBusinessMetricsDto.EngagementLike
                                    .builder()
                                    .percentage(0.0)
                                    .second("second")
                                    .build()
                            )
                            .favorites(0.0)
                            .fullVideoWatchedRate(0.0)
                            .addImpressionSource(
                                PlatformPost.Metrics.TikTokBusinessMetricsDto.ImpressionSource
                                    .builder()
                                    .impressionSource("impression_source")
                                    .percentage(0.0)
                                    .build()
                            )
                            .leadSubmissions(0.0)
                            .likes(0.0)
                            .newFollowers(0.0)
                            .phoneNumberClicks(0.0)
                            .profileViews(0.0)
                            .reach(0.0)
                            .shares(0.0)
                            .totalTimeWatched(0.0)
                            .addVideoViewRetention(
                                PlatformPost.Metrics.TikTokBusinessMetricsDto.VideoViewRetention
                                    .builder()
                                    .percentage(0.0)
                                    .second("second")
                                    .build()
                            )
                            .videoViews(0.0)
                            .websiteClicks(0.0)
                            .build()
                    )
                    .postedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .socialPostId("social_post_id")
                    .socialPostResultId("social_post_result_id")
                    .build()
            )
        assertThat(socialAccountFeedListResponse.meta())
            .isEqualTo(
                SocialAccountFeedListResponse.Meta.builder()
                    .cursor("cursor")
                    .limit(0.0)
                    .next("https://api.postforme.dev/v1/items?cursor=pgn_xxxxx&limit=10")
                    .hasMore(true)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val socialAccountFeedListResponse =
            SocialAccountFeedListResponse.builder()
                .addData(
                    PlatformPost.builder()
                        .caption("caption")
                        .addMedia(listOf(JsonValue.from(mapOf<String, Any>())))
                        .platform("platform")
                        .platformAccountId("platform_account_id")
                        .platformPostId("platform_post_id")
                        .platformUrl("platform_url")
                        .socialAccountId("social_account_id")
                        .externalAccountId("external_account_id")
                        .externalPostId("external_post_id")
                        .metrics(
                            PlatformPost.Metrics.TikTokBusinessMetricsDto.builder()
                                .addressClicks(0.0)
                                .appDownloadClicks(0.0)
                                .addAudienceCity(
                                    PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceCity
                                        .builder()
                                        .cityName("city_name")
                                        .percentage(0.0)
                                        .build()
                                )
                                .addAudienceCountry(
                                    PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceCountry
                                        .builder()
                                        .country("country")
                                        .percentage(0.0)
                                        .build()
                                )
                                .addAudienceGender(
                                    PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceGender
                                        .builder()
                                        .gender("gender")
                                        .percentage(0.0)
                                        .build()
                                )
                                .addAudienceType(
                                    PlatformPost.Metrics.TikTokBusinessMetricsDto.AudienceType
                                        .builder()
                                        .percentage(0.0)
                                        .type("type")
                                        .build()
                                )
                                .averageTimeWatched(0.0)
                                .comments(0.0)
                                .emailClicks(0.0)
                                .addEngagementLike(
                                    PlatformPost.Metrics.TikTokBusinessMetricsDto.EngagementLike
                                        .builder()
                                        .percentage(0.0)
                                        .second("second")
                                        .build()
                                )
                                .favorites(0.0)
                                .fullVideoWatchedRate(0.0)
                                .addImpressionSource(
                                    PlatformPost.Metrics.TikTokBusinessMetricsDto.ImpressionSource
                                        .builder()
                                        .impressionSource("impression_source")
                                        .percentage(0.0)
                                        .build()
                                )
                                .leadSubmissions(0.0)
                                .likes(0.0)
                                .newFollowers(0.0)
                                .phoneNumberClicks(0.0)
                                .profileViews(0.0)
                                .reach(0.0)
                                .shares(0.0)
                                .totalTimeWatched(0.0)
                                .addVideoViewRetention(
                                    PlatformPost.Metrics.TikTokBusinessMetricsDto.VideoViewRetention
                                        .builder()
                                        .percentage(0.0)
                                        .second("second")
                                        .build()
                                )
                                .videoViews(0.0)
                                .websiteClicks(0.0)
                                .build()
                        )
                        .postedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .socialPostId("social_post_id")
                        .socialPostResultId("social_post_result_id")
                        .build()
                )
                .meta(
                    SocialAccountFeedListResponse.Meta.builder()
                        .cursor("cursor")
                        .limit(0.0)
                        .next("https://api.postforme.dev/v1/items?cursor=pgn_xxxxx&limit=10")
                        .hasMore(true)
                        .build()
                )
                .build()

        val roundtrippedSocialAccountFeedListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(socialAccountFeedListResponse),
                jacksonTypeRef<SocialAccountFeedListResponse>(),
            )

        assertThat(roundtrippedSocialAccountFeedListResponse)
            .isEqualTo(socialAccountFeedListResponse)
    }
}
